sudo: required
language: python
dist: focal

cache: pip

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=doc
    - python: 3.6
      env: TOXENV=sphinx
    - python: 3.6
      env: TOXENV=lint
    - python: 2.7
      env: TOXENV=pep8py2
    - python: 3.6
      env: TOXENV=pep8py3
    - python: 3.6
      arch: ppc64le
      env: TOXENV=py36
    - python: 3.8
      env: TOXENV=py38
      arch: ppc64le

install:
  - sudo apt-get install cargo
  - pip install --upgrade pip setuptools
  - pip --version
  - pip install tox
  - tox --version

script:
  - tox
