{
    "name": "Release to PyPI",
    "on": {
        "push": {
            "tags": [ "v*.*" ]
        },
    },
    "jobs": {
        "pypi": {
            "name": "Publish Release",
            "runs-on": "ubuntu-latest",
            "steps": [
                { "uses": "actions/checkout@v2" },
                {
                    "uses": "actions/setup-python@v2",
                    "with": {
                        "python-version": "3.10"
                    },
                },
                { "run": "sudo apt-get update" },
                { "run": "sudo apt-get install cargo" },
                { "run": "pip --version" },
                { "run": "python setup.py sdist" },
                { "run": "python setup.py bdist_wheel" },
                {
                    "uses": "pypa/gh-action-pypi-publish@release/v1",
                    "with": {
                        "user": "__token__",
                        "password": "${{secrets.PYPI_API_TOKEN}}",
                        "skip-existing": true,
                    },
                },
            ],
        },
    },
}
